"""added parameter in model

Revision ID: 0d29fad93bb1
Revises: d75d7296a384
Create Date: 2025-02-16 16:57:03.487179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d29fad93bb1'
down_revision: Union[str, None] = 'd75d7296a384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_security_questions_user_id_fkey', 'user_security_questions', type_='foreignkey')
    op.drop_constraint('user_security_questions_question_id_fkey', 'user_security_questions', type_='foreignkey')
    op.create_foreign_key(None, 'user_security_questions', 'security_questions', ['question_id'], ['id'], source_schema='risk', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_security_questions', 'users', ['user_id'], ['id'], source_schema='risk', ondelete='CASCADE')
    op.add_column('users', sa.Column('answer_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'answer_verified')
    op.drop_constraint(None, 'user_security_questions', schema='risk', type_='foreignkey')
    op.drop_constraint(None, 'user_security_questions', schema='risk', type_='foreignkey')
    op.create_foreign_key('user_security_questions_question_id_fkey', 'user_security_questions', 'security_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_security_questions_user_id_fkey', 'user_security_questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
