"""stock model added

Revision ID: 1e77ec5c1738
Revises: 49a96c5f98b9
Create Date: 2025-03-05 12:31:09.320132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1e77ec5c1738'
down_revision: Union[str, None] = '49a96c5f98b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_prices',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('user_security_questions_user_id_fkey', 'user_security_questions', type_='foreignkey')
    op.drop_constraint('user_security_questions_question_id_fkey', 'user_security_questions', type_='foreignkey')
    op.create_foreign_key(None, 'user_security_questions', 'users', ['user_id'], ['id'], source_schema='risk', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_security_questions', 'security_questions', ['question_id'], ['id'], source_schema='risk', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_security_questions', schema='risk', type_='foreignkey')
    op.drop_constraint(None, 'user_security_questions', schema='risk', type_='foreignkey')
    op.create_foreign_key('user_security_questions_question_id_fkey', 'user_security_questions', 'security_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_security_questions_user_id_fkey', 'user_security_questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table('stock_prices')
    # ### end Alembic commands ###
