"""field added

Revision ID: 42669aa50648
Revises: e73c31d638c5
Create Date: 2025-02-22 12:49:14.570622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42669aa50648'
down_revision: Union[str, None] = 'e73c31d638c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_assessments', sa.Column('assesmentreport', sa.Text(), nullable=True))
    op.drop_constraint('user_security_questions_question_id_fkey', 'user_security_questions', type_='foreignkey')
    op.drop_constraint('user_security_questions_user_id_fkey', 'user_security_questions', type_='foreignkey')
    op.create_foreign_key(None, 'user_security_questions', 'security_questions', ['question_id'], ['id'], source_schema='risk', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_security_questions', 'users', ['user_id'], ['id'], source_schema='risk', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_security_questions', schema='risk', type_='foreignkey')
    op.drop_constraint(None, 'user_security_questions', schema='risk', type_='foreignkey')
    op.create_foreign_key('user_security_questions_user_id_fkey', 'user_security_questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_security_questions_question_id_fkey', 'user_security_questions', 'security_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_column('risk_assessments', 'assesmentreport')
    # ### end Alembic commands ###
