"""fields added in model

Revision ID: 49a96c5f98b9
Revises: 42669aa50648
Create Date: 2025-02-24 15:45:51.522673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a96c5f98b9'
down_revision: Union[str, None] = '42669aa50648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_security_questions_question_id_fkey', 'user_security_questions', type_='foreignkey')
    op.drop_constraint('user_security_questions_user_id_fkey', 'user_security_questions', type_='foreignkey')
    op.create_foreign_key(None, 'user_security_questions', 'security_questions', ['question_id'], ['id'], source_schema='risk', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_security_questions', 'users', ['user_id'], ['id'], source_schema='risk', ondelete='CASCADE')
    op.add_column('users', sa.Column('phoneotp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phoneno_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('privacy_policy', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('terms_condition', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('apartment', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('earning', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('profile_question_response', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_question_response')
    op.drop_column('users', 'earning')
    op.drop_column('users', 'apartment')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'terms_condition')
    op.drop_column('users', 'privacy_policy')
    op.drop_column('users', 'phoneno_verified')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'phoneotp')
    op.drop_constraint(None, 'user_security_questions', schema='risk', type_='foreignkey')
    op.drop_constraint(None, 'user_security_questions', schema='risk', type_='foreignkey')
    op.create_foreign_key('user_security_questions_user_id_fkey', 'user_security_questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_security_questions_question_id_fkey', 'user_security_questions', 'security_questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
