"""risk module

Revision ID: bb3f7e68df1b
Revises: a8a16686b56f
Create Date: 2025-02-21 14:18:48.074009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bb3f7e68df1b'
down_revision: Union[str, None] = 'a8a16686b56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('conversation_history', sa.JSON(), nullable=False),
    sa.Column('sec_lang', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('user_security_questions_user_id_fkey', 'user_security_questions', type_='foreignkey')
    op.drop_constraint('user_security_questions_question_id_fkey', 'user_security_questions', type_='foreignkey')
    op.create_foreign_key(None, 'user_security_questions', 'users', ['user_id'], ['id'], source_schema='risk', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_security_questions', 'security_questions', ['question_id'], ['id'], source_schema='risk', ondelete='CASCADE')
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('pincode', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('employment_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avg_investment', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('secondary_language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_complete')
    op.drop_column('users', 'secondary_language')
    op.drop_column('users', 'avg_investment')
    op.drop_column('users', 'employment_status')
    op.drop_column('users', 'pincode')
    op.drop_column('users', 'country')
    op.drop_column('users', 'address')
    op.drop_constraint(None, 'user_security_questions', schema='risk', type_='foreignkey')
    op.drop_constraint(None, 'user_security_questions', schema='risk', type_='foreignkey')
    op.create_foreign_key('user_security_questions_question_id_fkey', 'user_security_questions', 'security_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_security_questions_user_id_fkey', 'user_security_questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
